deploy:
  stage: deploy
  image: ruby:latest
  environment:
    name: development
    url: https://dev-gostivarapp.herokuapp.com/
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=gostivarapp-dev --api-key=17b6a43e-67be-43d7-820a-b9ae80ef66b6
  only:
    - master