image: node:latest

stages:
  - deploy
  
deploy:
  environment: development
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=dev-gostivarapp --api-key=$DEV_HEROKU_API_KEY
  only:
    - master