cache:
  paths:
    - node_modules/
    
stages:
  - development
  
deploy:
  type: deploy
  stage: development
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - master